[platformio]
default_envs = jc4827w543

[env:jc4827w543]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board    = esp32-s3-devkitc-1
framework = arduino

monitor_speed   = 115200
monitor_filters = esp32_exception_decoder
upload_speed    = 921600

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
    -DJC4827W543_DISPLAY=1
    -DSCREEN_WIDTH=480
    -DSCREEN_HEIGHT=272
    -DTFT_CS=45
    -DTFT_SCK=47
    -DTFT_D0=21
    -DTFT_D1=48
    -DTFT_D2=40
    -DTFT_D3=39
    -DTFT_BL=1
    -DTOUCH_MODULES_GT911
    -DTOUCH_SCL=4
    -DTOUCH_SDA=8
    -DTOUCH_RST=38
    -DTOUCH_INT=3
    -DLV_CONF_INCLUDE_SIMPLE=1
    -DLV_LVGL_H_INCLUDE_SIMPLE=1
    -I.

lib_deps =
    lvgl/lvgl@8.4.0
    moononournation/GFX Library for Arduino@^1.4.6
    https://github.com/mmMicky/TouchLib.git
    mathieucarbou/ESPAsyncWebServer@^3.3.8

board_build.partitions      = huge_app.csv
board_build.arduino.memory_type = qio_opi
